### ISSUE TITLE
Weapons that use "burst count" might be differently ballanced than intended regarding "reload"

### ISSUE THREAD

**Issue by cola98765** [1010todd/Mega-Freight#3]
when using "burst count", "reload" means 'frames to reload single round' not whole salvo.

example:
M6-ACS Artillery
98t
single barrel icon
reload
"reload" 60
1 shot/s

M6-ACS Artillery Turret
280t (I'm willing to give 50% turret overhead)
2 barrel icon
"reload" 60
2 shots then 2s reload time averaging 1 shot/s

additionally lack of "cluster" tag makes it so even if you fire single shot it waits those 2s, where with this tag it will wait till you fire that other barrel

**Comment by 1010todd** [comment]
Most likely I've forgot to half the reload for gun version, it was made a bit after the turret. Thanks for reporting, I'll fix it in the next update.

**Comment by 1010todd** [comment]
Fixed in d615837b0fef20b18b04e7557cbfd6a612ddf2ee .
