### ISSUE TITLE
LXC-2 Strata ship is missing gun ports.

### ISSUE THREAD

**Issue by 43897689431805741092** [1010todd/Mega-Freight#5]
The thumbnail view of its model reveals it has two holes for gun ports at the front, like the other tankers, but it's currently missing actual gun port data. I came up with approximate positions (below) but as the modeller you'd have a better idea since they're not visible from the top view.

```
	gun -23.5 -220 
	gun 23.5 -220 
```

**Comment by 1010todd** [comment]
I'll fix it in the next update. Thanks for the report.

**Comment by 1010todd** [comment]
Should be solved with [58d9a99](https://github.com/1010todd/Mega-Freight/commit/58d9a99a0d86e593c352afb61d6f8e99112b74b9)
